/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import AnualidadAnticipada.aAnualidadconVFA;
import AnualidadAnticipada.aAnualidadconVPA;
import AnualidadAnticipada.aValorFinalA;
import AnualidadAnticipada.aValorPresenteA;
import AnualidadAnticipada.anPerA;
import AnualidadPerpetua.aValorPresenteP;
import AnualidadVencida.aNperV;
import AnualidadVencida.aValorFinalV;
import AnualidadVencida.aValorPresenteV;
import AnualidadVencida.anualidadconVFV;
import AnualidadVencida.anualidadconVPV;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ConversionDeTasas.iE;
import ConversionDeTasas.iEA;
import ConversionDeTasas.iNA;
import ConversionDeTasas.iNom;
import GradienteGeometricoCreciente.gAidifejVPGGC;
import GradienteGeometricoCreciente.gAiigualjVFGGC;
import GradienteGeometricoCreciente.gCalcularCuotaGGC;
import GradienteGeometricoCreciente.gVFGGC;
import GradienteGeometricoCreciente.gVPidifejGGC;
import GradienteGeometricoCreciente.gVPiigualjGGC;
import GradienteGeometricoDecreciente.gVPidifejGGD;
import GradienteGeometricoDecreciente.gVPiigualjGGD;
import GradienteLinealCreciente.gAGLC;
import GradienteLinealCreciente.gVFGLC;
import GradienteLinealCreciente.gVPGLC;
import GradienteLinealDecreciente.gCalcularCuota;
import InteresCompuesto.cVA;
import InteresCompuesto.cVF;
import InteresCompuesto.ci;
import InteresCompuesto.cnPer;
import InteresSimple.VF;
import InteresSimple.VA;
import InteresSimple.i;
import InteresSimple.nPer;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Adrian AC
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form AplicarTeoríacreandoConjuntos
     */
    public Principal() {
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
//        Ayuda.setMinimumSize(new Dimension(700, 332));
//        Ayuda.setLocationRelativeTo(this);
//        Ayuda.setVisible(true);
//        Ayuda.setAlwaysOnTop(true);
//        Ayuda.setModal(true);
        
          Ayuda  ayuda= new Ayuda();
            Escritorio.add(ayuda);
            ayuda.show();
        setIconImage (new ImageIcon(getClass().getResource("../img/ico.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Integrantes = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Ayuda = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        Escritorio = new javax.swing.JDesktopPane();
        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnInteresSimple = new javax.swing.JButton();
        btnInteresCompuesto = new javax.swing.JButton();
        btnAnualidVencida = new javax.swing.JButton();
        btnTasa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        btnAnualidAnticipada = new javax.swing.JButton();
        btnAnualidPerpetua = new javax.swing.JButton();
        btnGLD = new javax.swing.JButton();
        btnGLC = new javax.swing.JButton();
        btnGGC = new javax.swing.JButton();
        btnGGD = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnSalir3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 0));

        jLabel6.setFont(new java.awt.Font("Ebrima", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Matematica Financiera");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jLabel7.setBackground(new java.awt.Color(0, 0, 102));
        jLabel7.setFont(new java.awt.Font("Ebrima", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Adrian Andres Atencia Caly");

        jLabel8.setBackground(new java.awt.Color(0, 0, 102));
        jLabel8.setFont(new java.awt.Font("Ebrima", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Helen Margarita Montes Dagobeth");

        jLabel10.setBackground(new java.awt.Color(0, 0, 102));
        jLabel10.setFont(new java.awt.Font("Ebrima", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Ingenieria de sistemas VI semestre                                                                             Presentado a:  Ing. Andrea Burbano");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(275, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)))
        );

        javax.swing.GroupLayout IntegrantesLayout = new javax.swing.GroupLayout(Integrantes.getContentPane());
        Integrantes.getContentPane().setLayout(IntegrantesLayout);
        IntegrantesLayout.setHorizontalGroup(
            IntegrantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        IntegrantesLayout.setVerticalGroup(
            IntegrantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 51, 0));

        jLabel9.setFont(new java.awt.Font("Ebrima", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Matematicas Financiera");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tips");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(102, 102, 102))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel13.setBackground(new java.awt.Color(0, 0, 102));
        jLabel13.setFont(new java.awt.Font("Ebrima", 3, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Ingenieria de sistemas VI semestre                                                                             Presentado a:  Andrea Burbano");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("El valor de la nota para\nlos integrantes debe ser de  \n4.9 a 5.0");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tip 3"));
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Para el ingreso de valores de \nla tasa de interes se debe ingresar\nel valor ya dividido entre 100.\nejemplo:\nsi la tasa es del 30% se debe ingresar\nsu valor convertido en 0.3\n");
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tip 1"));
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("advertencia: para el buen funcionamiento\ny calculo los valores decimales debes ser \nseparados por un punto (.) sin espacios.");
        jTextArea3.setAutoscrolls(false);
        jTextArea3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tip 2"));
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(275, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)))
        );

        javax.swing.GroupLayout AyudaLayout = new javax.swing.GroupLayout(Ayuda.getContentPane());
        Ayuda.getContentPane().setLayout(AyudaLayout);
        AyudaLayout.setHorizontalGroup(
            AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AyudaLayout.setVerticalGroup(
            AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Soft-Finanzas");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);

        Escritorio.setBackground(new java.awt.Color(255, 255, 255));
        Escritorio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true));

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowBottomShadow(false);
        pnlMenu.setBorder(dropShadowBorder1);
        pnlMenu.setToolTipText("Opciones");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        btnInteresSimple.setBackground(new java.awt.Color(0, 51, 0));
        btnInteresSimple.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInteresSimple.setForeground(new java.awt.Color(255, 255, 255));
        btnInteresSimple.setText("Interés Simple");
        btnInteresSimple.setToolTipText("Interés Simple");
        btnInteresSimple.setBorder(null);
        btnInteresSimple.setContentAreaFilled(false);
        btnInteresSimple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInteresSimple.setOpaque(true);
        btnInteresSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteresSimpleActionPerformed(evt);
            }
        });

        btnInteresCompuesto.setBackground(new java.awt.Color(0, 51, 0));
        btnInteresCompuesto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInteresCompuesto.setForeground(new java.awt.Color(255, 255, 255));
        btnInteresCompuesto.setText("Interés compuesto");
        btnInteresCompuesto.setToolTipText("Interés compuesto");
        btnInteresCompuesto.setBorder(null);
        btnInteresCompuesto.setContentAreaFilled(false);
        btnInteresCompuesto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInteresCompuesto.setOpaque(true);
        btnInteresCompuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteresCompuestoActionPerformed(evt);
            }
        });

        btnAnualidVencida.setBackground(new java.awt.Color(0, 51, 0));
        btnAnualidVencida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAnualidVencida.setForeground(new java.awt.Color(255, 255, 255));
        btnAnualidVencida.setText("Anualidad Vencida");
        btnAnualidVencida.setToolTipText("Anualidad Vencida");
        btnAnualidVencida.setBorder(null);
        btnAnualidVencida.setContentAreaFilled(false);
        btnAnualidVencida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnualidVencida.setOpaque(true);
        btnAnualidVencida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnualidVencidaActionPerformed(evt);
            }
        });

        btnTasa.setBackground(new java.awt.Color(0, 51, 0));
        btnTasa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTasa.setForeground(new java.awt.Color(255, 255, 255));
        btnTasa.setText("Conversión de tasas");
        btnTasa.setToolTipText("Conversión de tasas");
        btnTasa.setBorder(null);
        btnTasa.setContentAreaFilled(false);
        btnTasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTasa.setOpaque(true);
        btnTasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTasaActionPerformed(evt);
            }
        });

        jLabel2.setText("Soft-Finanzas");

        btnAyuda.setBackground(new java.awt.Color(0, 51, 0));
        btnAyuda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAyuda.setForeground(new java.awt.Color(255, 255, 255));
        btnAyuda.setText("Integrantes");
        btnAyuda.setBorder(null);
        btnAyuda.setContentAreaFilled(false);
        btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAyuda.setOpaque(true);
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        btnAnualidAnticipada.setBackground(new java.awt.Color(0, 51, 0));
        btnAnualidAnticipada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAnualidAnticipada.setForeground(new java.awt.Color(255, 255, 255));
        btnAnualidAnticipada.setText("Anualidad Anticipada");
        btnAnualidAnticipada.setToolTipText("Anualidad Anticipada");
        btnAnualidAnticipada.setBorder(null);
        btnAnualidAnticipada.setContentAreaFilled(false);
        btnAnualidAnticipada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnualidAnticipada.setOpaque(true);
        btnAnualidAnticipada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnualidAnticipadaActionPerformed(evt);
            }
        });

        btnAnualidPerpetua.setBackground(new java.awt.Color(0, 51, 0));
        btnAnualidPerpetua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAnualidPerpetua.setForeground(new java.awt.Color(255, 255, 255));
        btnAnualidPerpetua.setText("Anualidad Perpetua");
        btnAnualidPerpetua.setToolTipText("Anualidad Perpetua");
        btnAnualidPerpetua.setBorder(null);
        btnAnualidPerpetua.setContentAreaFilled(false);
        btnAnualidPerpetua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnualidPerpetua.setOpaque(true);
        btnAnualidPerpetua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnualidPerpetuaActionPerformed(evt);
            }
        });

        btnGLD.setBackground(new java.awt.Color(0, 51, 0));
        btnGLD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGLD.setForeground(new java.awt.Color(255, 255, 255));
        btnGLD.setText("G.L.D");
        btnGLD.setToolTipText("Gradiente Lineal Decreciente");
        btnGLD.setBorder(null);
        btnGLD.setContentAreaFilled(false);
        btnGLD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGLD.setOpaque(true);
        btnGLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGLDActionPerformed(evt);
            }
        });

        btnGLC.setBackground(new java.awt.Color(0, 51, 0));
        btnGLC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGLC.setForeground(new java.awt.Color(255, 255, 255));
        btnGLC.setText("G.L.C");
        btnGLC.setToolTipText("Gradiente Lineal Creciente");
        btnGLC.setBorder(null);
        btnGLC.setContentAreaFilled(false);
        btnGLC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGLC.setOpaque(true);
        btnGLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGLCActionPerformed(evt);
            }
        });

        btnGGC.setBackground(new java.awt.Color(0, 51, 0));
        btnGGC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGGC.setForeground(new java.awt.Color(255, 255, 255));
        btnGGC.setText("G.G.C");
        btnGGC.setToolTipText("Gradiente Geometrico Creciente");
        btnGGC.setBorder(null);
        btnGGC.setContentAreaFilled(false);
        btnGGC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGGC.setOpaque(true);
        btnGGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGGCActionPerformed(evt);
            }
        });

        btnGGD.setBackground(new java.awt.Color(0, 51, 0));
        btnGGD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGGD.setForeground(new java.awt.Color(255, 255, 255));
        btnGGD.setText("G.G.D");
        btnGGD.setToolTipText("Gradiente Geometrico Decreciente");
        btnGGD.setBorder(null);
        btnGGD.setContentAreaFilled(false);
        btnGGD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGGD.setOpaque(true);
        btnGGD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGGDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInteresSimple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInteresCompuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAnualidVencida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(64, 64, 64))
            .addComponent(btnAnualidPerpetua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAnualidAnticipada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGLC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGLD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGGC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGGD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAyuda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInteresSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInteresCompuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnualidVencida, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnualidAnticipada, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnualidPerpetua, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnGLC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGLD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGGC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGGD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnAyuda)
                .addContainerGap())
        );

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Entypo_2630(0)_64.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Entypo_e005(0)_64.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 51, 0));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("X");
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setOpaque(true);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnSalir3.setBackground(new java.awt.Color(0, 51, 0));
        btnSalir3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSalir3.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir3.setText("-");
        btnSalir3.setBorder(null);
        btnSalir3.setContentAreaFilled(false);
        btnSalir3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir3.setOpaque(true);
        btnSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir3ActionPerformed(evt);
            }
        });

        Escritorio.setLayer(pnlMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(btnMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(btnSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(btnSalir3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 988, Short.MAX_VALUE)
                .addComponent(btnSalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu)
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        int posicion = btnMenu.getX();
        if (posicion > 5) {
            Animacion.Animacion.mover_izquierda(211, 5, 2, 2, btnMenu);
            Animacion.Animacion.mover_izquierda(5, -200, 2, 2, pnlMenu);
        } else {
            Animacion.Animacion.mover_derecha(5, 210, 2, 2, btnMenu);
            Animacion.Animacion.mover_derecha(-200, 5, 2, 2, pnlMenu);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInteresSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteresSimpleActionPerformed

        String[] opcion = {
            "Valor Inicial (VP)",
            "Valor Final (VF)",
            "Tasa de interes (i)",
            "Numero de periodos (Nper)",};
        MyIconS icon = new MyIconS();
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione un calculo a realizar", "Calculo Interes Simple", JOptionPane.DEFAULT_OPTION, icon, opcion, opcion[0]);

        if ("Valor Inicial (VP)".equals(resp)) {
            //JOptionPane.showMessageDialog(null, "Valor Inicial (VA) ");
            VA vp = new VA();
            Escritorio.add(vp);
            vp.show();
        }
        if ("Valor Final (VF)".equals(resp)) {
            //JOptionPane.showMessageDialog(null, "Valor Final");
            VF vf = new VF();
            Escritorio.add(vf);
            vf.show();
        }
        if ("Tasa de interes (i)".equals(resp)) {
            //JOptionPane.showMessageDialog(null, "Tasa de intere");
            i i = new i();
            Escritorio.add(i);
            i.show();
        }
        if ("Numero de periodos (Nper)".equals(resp)) {
            // JOptionPane.showMessageDialog(null, "Numero de periodos");
            nPer n = new nPer();
            Escritorio.add(n);
            n.show();
        }


    }//GEN-LAST:event_btnInteresSimpleActionPerformed

    private void btnInteresCompuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteresCompuestoActionPerformed
        String[] opcion = {
            "Valor Inicial (VP)",
            "Valor Final (VF)",
            "Tasa de interes (i)",
            "Numero de periodos (Nper)",};
        MyIconC icon = new MyIconC();
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione un calculo a realizar", "Calculo Interes Compuesto", JOptionPane.DEFAULT_OPTION, icon, opcion, opcion[0]);
        if ("Valor Inicial (VA)".equals(resp)) {
            //JOptionPane.showMessageDialog(null, "Valor Inicial (VA) ");
            cVA vp = new cVA();
            Escritorio.add(vp);
            vp.show();
        }
        if ("Valor Final (VF)".equals(resp)) {
            //JOptionPane.showMessageDialog(null, "Valor Final");
            cVF vf = new cVF();
            Escritorio.add(vf);
            vf.show();
        }
        if ("Tasa de interes (i)".equals(resp)) {
            JOptionPane.showMessageDialog(null, "Tasa de intere");
            ci i = new ci();
            Escritorio.add(i);
            i.show();
        }
        if ("Numero de periodos (Nper)".equals(resp)) {
            JOptionPane.showMessageDialog(null, "Numero de periodos");
            cnPer n = new cnPer();
            Escritorio.add(n);
            n.show();
        }
    }//GEN-LAST:event_btnInteresCompuestoActionPerformed

    private void btnTasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTasaActionPerformed
        String[] opcion = {
            "Nominal a Efectiva",
            "Efectiva a Nomina",
            "Efectiva Anual a Efectiva Periódica",
            "Efectiva periódica a Efectiva Anual",};
        MyIconT icon = new MyIconT();
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione un calculo a realizar", "Conversión de tasas", JOptionPane.DEFAULT_OPTION, icon, opcion, opcion[0]);
        if ("Nominal a Efectiva".equals(resp)) {
            iE ie = new iE();
            Escritorio.add(ie);
            ie.show();
            JOptionPane.showMessageDialog(null, "Nominal a Efectiva");
        }
        if ("Efectiva a Nomina".equals(resp)) {
            iNom inom = new iNom();
            Escritorio.add(inom);
            inom.show();
            JOptionPane.showMessageDialog(null, "Efectiva a Nomina");
        }
        if ("Efectiva Anual a Efectiva Periódica".equals(resp)) {
            iEA iea = new iEA();
            Escritorio.add(iea);
            iea.show();
            JOptionPane.showMessageDialog(null, "Efectiva Anual a Efectiva Periódica");
        }
        if ("Efectiva periódica a Efectiva Anual".equals(resp)) {
            iNA ina = new iNA();
            Escritorio.add(ina);
            ina.show();
            JOptionPane.showMessageDialog(null, "Efectiva periódica a Efectiva Anual");
        }
    }//GEN-LAST:event_btnTasaActionPerformed

    private void btnAnualidVencidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnualidVencidaActionPerformed
        String[] opcion = {
            "Valor Presente (VP)",
            "Valor Final (VF)",
            "Anualidad (A)",
            "Numero de periodos (Nper)",};
        MyIconA icon = new MyIconA();
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione un calculo a realizar", "Anualidades Vencidas", JOptionPane.DEFAULT_OPTION, icon, opcion, opcion[0]);
        if ("Valor Presente (VP)".equals(resp)) {

            aValorPresenteV aVP = new aValorPresenteV();
            Escritorio.add(aVP);
            aVP.show();
           // JOptionPane.showMessageDialog(null, "");
        }
        if ("Valor Final (VF)".equals(resp)) {
            aValorFinalV aVF = new aValorFinalV();
            Escritorio.add(aVF);
            aVF.show();
           // JOptionPane.showMessageDialog(null, "Valor Final (VF)");
        }

        if ("Anualidad (A)".equals(resp)) {
            MyIconC icono = new MyIconC();
            String[] options = {"Valor Presente", "Valor Final"};
            int seleccion = JOptionPane.showOptionDialog(null, "Que valor tiene para calcular la anualidad ", "Opcion", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, icono, options, options[0]);
            if (seleccion == 0) {
                anualidadconVPV a = new anualidadconVPV();
                Escritorio.add(a);
                a.show();
               // JOptionPane.showMessageDialog(null, "Anualidad con vp (A)");
            }
            if (seleccion == 1) {
                anualidadconVFV a = new anualidadconVFV();
                Escritorio.add(a);
                a.show();
                //JOptionPane.showMessageDialog(null, "Anualidad con vp (A)");
            }

           // JOptionPane.showMessageDialog(null, "Anualidad (A)");
        }
        if ("Numero de periodos (Nper)".equals(resp)) {

            aNperV aNP = new aNperV();
            Escritorio.add(aNP);
            aNP.show();

           // JOptionPane.showMessageDialog(null, "Numero de periodos (Nper)");
        }


    }//GEN-LAST:event_btnAnualidVencidaActionPerformed

    private void btnGLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGLCActionPerformed
        String[] opcion = {
            "Valor Presente (VP)",
            "Valor Final (VF)",
            "Anualidad (A)",};
        MyIconA icon = new MyIconA();
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione un calculo a realizar", "Gradiente Lineal Creciente", JOptionPane.DEFAULT_OPTION, icon, opcion, opcion[0]);
        if ("Valor Presente (VP)".equals(resp)) {
            gVPGLC gvpglc = new gVPGLC();
            Escritorio.add(gvpglc);
            gvpglc.show();
            //JOptionPane.showMessageDialog(null, "Valor Presente (VP)");
        }
        if ("Valor Final (VF)".equals(resp)) {
            gVFGLC gvfglc = new gVFGLC();
            Escritorio.add(gvfglc);
            gvfglc.show();
            //JOptionPane.showMessageDialog(null, "Valor Final (VF)");
        }
        if ("Anualidad (A)".equals(resp)) {
            gAGLC gapglc = new gAGLC();
            Escritorio.add(gapglc);
            gapglc.show();
           // JOptionPane.showMessageDialog(null, "Anualidad (A)");
        }

    }//GEN-LAST:event_btnGLCActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        Integrantes.setMinimumSize(new Dimension(680, 332));
        Integrantes.setLocationRelativeTo(this);
        Integrantes.setVisible(true);
        Integrantes.setAlwaysOnTop(true);
        Integrantes.setModal(true);
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnAnualidAnticipadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnualidAnticipadaActionPerformed
        String[] opcion = {
            "Valor Presente (VP)",
            "Valor Final (VF)",
            "Anualidad (A)",
            "Numero de periodos (Nper)",};
        MyIconA icon = new MyIconA();
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione un calculo a realizar", "Anualidades Anticipadas", JOptionPane.DEFAULT_OPTION, icon, opcion, opcion[0]);
        if ("Valor Presente (VP)".equals(resp)) {

            aValorPresenteA aVPA = new aValorPresenteA();
            Escritorio.add(aVPA);
            aVPA.show();
           // JOptionPane.showMessageDialog(null, "Valor Presente (VP)");

        }
        if ("Valor Final (VF)".equals(resp)) {

            aValorFinalA aVFA = new aValorFinalA();
            Escritorio.add(aVFA);
            aVFA.show();
          //  JOptionPane.showMessageDialog(null, "Valor Final (VF)");

        }

        if ("Anualidad (A)".equals(resp)) {

            MyIconC icono = new MyIconC();
            String[] options = {"Valor Presente", "Valor Final"};
            int seleccion = JOptionPane.showOptionDialog(null, "Que valor tiene para calcular la anualidad ", "Opcion", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, icono, options, options[0]);
            if (seleccion == 0) {
                aAnualidadconVPA aAA = new aAnualidadconVPA();
                Escritorio.add(aAA);
                aAA.show();

              //  JOptionPane.showMessageDialog(null, "Anualidad con vp (A)");
            }
            if (seleccion == 1) {
                aAnualidadconVFA aVFA = new aAnualidadconVFA();
                Escritorio.add(aVFA);
                aVFA.show();
            }

            //JOptionPane.showMessageDialog(null, "Anualidad");

        }
        if ("Numero de periodos (Nper)".equals(resp)) {
            anPerA aNPA = new anPerA();
            Escritorio.add(aNPA);
            aNPA.show();
            //JOptionPane.showMessageDialog(null, "Numero de periodos (Nper)");
        }
    }//GEN-LAST:event_btnAnualidAnticipadaActionPerformed

    private void btnAnualidPerpetuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnualidPerpetuaActionPerformed
        aValorPresenteP aVPP = new aValorPresenteP();
        Escritorio.add(aVPP);
        aVPP.show();
        //JOptionPane.showMessageDialog(null, "Anualidad Perpetua");
    }//GEN-LAST:event_btnAnualidPerpetuaActionPerformed

    private void btnSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir3ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnSalir3ActionPerformed

    private void btnGLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGLDActionPerformed
        String[] opcion = {
            "Valor Presente (VP)",
            "Cuota Cn",};
        MyIconA icon = new MyIconA();
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione un calculo a realizar", "Gradiente Lineal Decreciente", JOptionPane.DEFAULT_OPTION, icon, opcion, opcion[0]);
        if ("Valor Presente (VP)".equals(resp)) {
            gVPGLC gvpglc = new gVPGLC();
            Escritorio.add(gvpglc);
            gvpglc.show();
           // JOptionPane.showMessageDialog(null, "Valor Presente (VP)");
        }
        if ("Cuota Cn".equals(resp)) {
            gCalcularCuota gcd = new gCalcularCuota();
            Escritorio.add(gcd);
            gcd.show();
           // JOptionPane.showMessageDialog(null, "Cuota");
        }

    }//GEN-LAST:event_btnGLDActionPerformed

    private void btnGGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGGCActionPerformed
        String[] opcion = {
            "Valor Presente (VP)",
            "Valor Final (VF)",
            "Anualidad (A)",
            "Cuota Cn",};
        MyIconA icon = new MyIconA();
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione un calculo a realizar", "Gradiente Geometrico Creciente", JOptionPane.DEFAULT_OPTION, icon, opcion, opcion[0]);
        if ("Valor Presente (VP)".equals(resp)) {

            MyIconC icono = new MyIconC();
            String[] options = {"Para i ≠ j", "Para i = j"};
            int seleccion = JOptionPane.showOptionDialog(null, "Para i ?", "Opcion", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, icono, options, options[0]);
            if (seleccion == 0) {
                gVPidifejGGC avpdife = new gVPidifejGGC();
                Escritorio.add(avpdife);
                avpdife.show();

                //JOptionPane.showMessageDialog(null, "Anualidad con vp (A)");
            }
            if (seleccion == 1) {
                gVPiigualjGGC avpigual = new gVPiigualjGGC();
                Escritorio.add(avpigual);
                avpigual.show();
            }
            //JOptionPane.showMessageDialog(null, "Valor Presente (VP)");
        }
        if ("Anualidad (A)".equals(resp)) {

            MyIconC icono = new MyIconC();
            String[] options = {"Calcular con valor presente (VP)", "Calcular con valor final (VF)"};
            int seleccion = JOptionPane.showOptionDialog(null, "Que valor tiene para calcular la anualidad", "Opcion", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, icono, options, options[0]);
            if (seleccion == 0) {
                gAidifejVPGGC avpdife = new gAidifejVPGGC();
                Escritorio.add(avpdife);
                avpdife.show();

                //JOptionPane.showMessageDialog(null, "Anualidad con vp (A)");
            }
            if (seleccion == 1) {
                gAiigualjVFGGC avpigual = new gAiigualjVFGGC();
                Escritorio.add(avpigual);
                avpigual.show();
            }
            //JOptionPane.showMessageDialog(null, "Valor Presente (VP)");
        }
        if ("Valor Final (VF)".equals(resp)) {
            gVFGGC gcd = new gVFGGC();
            Escritorio.add(gcd);
            gcd.show();
           // JOptionPane.showMessageDialog(null, "Cuota");
        }
        if ("Cuota Cn".equals(resp)) {
            gCalcularCuotaGGC gcd = new gCalcularCuotaGGC();
            Escritorio.add(gcd);
            gcd.show();
            //JOptionPane.showMessageDialog(null, "Cuota");
        }
    }//GEN-LAST:event_btnGGCActionPerformed

    private void btnGGDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGGDActionPerformed
        String[] opcion = {
            "Valor Presente (VP)",
            "Cuota Cn",};
        MyIconA icon = new MyIconA();
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione un calculo a realizar", "Gradiente Geometrico Creciente", JOptionPane.DEFAULT_OPTION, icon, opcion, opcion[0]);
        if ("Valor Presente (VP)".equals(resp)) {

            MyIconC icono = new MyIconC();
            String[] options = {"Para i ≠ j", "Para i = j"};
            int seleccion = JOptionPane.showOptionDialog(null, "Para i ?", "Opcion", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, icono, options, options[0]);
            if (seleccion == 0) {
                gVPidifejGGD avpdife = new gVPidifejGGD();
                Escritorio.add(avpdife);
                avpdife.show();

              //  JOptionPane.showMessageDialog(null, "Anualidad con vp (A)");
            }
            if (seleccion == 1) {
                gVPiigualjGGD avpigual = new gVPiigualjGGD();
                Escritorio.add(avpigual);
                avpigual.show();
            }
           // JOptionPane.showMessageDialog(null, "Valor Presente (VP)");
        }

        if ("Cuota Cn".equals(resp)) {
            gCalcularCuotaGGC gcd = new gCalcularCuotaGGC();
            Escritorio.add(gcd);
            gcd.show();
           // JOptionPane.showMessageDialog(null, "Cuota");
        }
    }//GEN-LAST:event_btnGGDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
//Simple

    public class MyIconS implements Icon {

        @Override
        public void paintIcon(Component c, Graphics g, int x, int y) {
            Image image1 = new ImageIcon(getClass().getResource("/img/ico.png")).getImage();
            g.drawImage(image1, x, y, c);
        }

        @Override
        public int getIconWidth() {
            return 50;
        }

        @Override
        public int getIconHeight() {
            return 50;
        }

    }
//Compuesto

    public class MyIconC implements Icon {

        @Override
        public void paintIcon(Component c, Graphics g, int x, int y) {
            Image image1 = new ImageIcon(getClass().getResource("/img/compuesto.png")).getImage();
            g.drawImage(image1, x, y, c);
        }

        @Override
        public int getIconWidth() {
            return 50;
        }

        @Override
        public int getIconHeight() {
            return 50;
        }

    }
    //Tasas

    public class MyIconT implements Icon {

        @Override
        public void paintIcon(Component c, Graphics g, int x, int y) {
            Image image1 = new ImageIcon(getClass().getResource("/img/conversion.png")).getImage();
            g.drawImage(image1, x, y, c);
        }

        @Override
        public int getIconWidth() {
            return 50;
        }

        @Override
        public int getIconHeight() {
            return 50;
        }

    }
//Anualidades
    //Gradientes

    public class MyIconA implements Icon {

        @Override
        public void paintIcon(Component c, Graphics g, int x, int y) {
            Image image1 = new ImageIcon(getClass().getResource("/img/anualidades-gradiente.png")).getImage();
            g.drawImage(image1, x, y, c);
        }

        @Override
        public int getIconWidth() {
            return 50;
        }

        @Override
        public int getIconHeight() {
            return 50;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Ayuda;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JDialog Integrantes;
    private javax.swing.JButton btnAnualidAnticipada;
    private javax.swing.JButton btnAnualidPerpetua;
    private javax.swing.JButton btnAnualidVencida;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnGGC;
    private javax.swing.JButton btnGGD;
    private javax.swing.JButton btnGLC;
    private javax.swing.JButton btnGLD;
    private javax.swing.JButton btnInteresCompuesto;
    private javax.swing.JButton btnInteresSimple;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir3;
    private javax.swing.JButton btnTasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
